In [1]:
import pandas as pd

In [2]:
health_remote_df = pd.read_csv('health-remote-work-v3.csv')
health_remote_df

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,EMP0001,32,Non-binary,HR,Healthcare,13,Remote,43,7,2,Medium,Depression,No,Decrease,4,Satisfied,1,Weekly,Good,Europe
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,48,4,1,Medium,Anxiety,No,Increase,2,Unsatisfied,2,Weekly,Good,Asia
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,43,11,5,Medium,Anxiety,No,No Change,4,Satisfied,5,NaN,Poor,North America
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,59,8,4,High,Anxiety,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,57,12,2,High,Anxiety,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,EMP14996,32,Male,Sales,Consulting,4,Remote,50,2,5,High,Depression,Yes,Decrease,2,Unsatisfied,1,Weekly,Average,Asia
14996,EMP14997,39,Female,Sales,Healthcare,27,Onsite,44,15,1,Low,NaN,Yes,Decrease,2,Unsatisfied,1,NaN,Average,Africa
14997,EMP14998,42,Female,Sales,Healthcare,21,Remote,41,1,4,High,Anxiety,No,Increase,4,Satisfied,1,Daily,Poor,Oceania
14998,EMP14999,27,Female,Sales,Healthcare,26,Remote,27,0,5,Low,NaN,Yes,Increase,5,Neutral,4,Daily,Average,Asia
14999,EMP15000,29,Male,HR,IT,30,Hybrid,59,15,1,Low,NaN,Yes,No Change,1,Unsatisfied,5,NaN,Poor,Asia

In [4]:
health_remote_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Employee_ID                        15000 non-null  object
 1   Age                                15000 non-null  int64
 2   Gender                             15000 non-null  object
 3   Job_Role                           15000 non-null  object
 4   Industry                           15000 non-null  object
 5   Years_of_Experience                15000 non-null  int64
 6   Work_Location                      15000 non-null  object
 7   Hours_Worked_Per_Week              15000 non-null  int64
 8   Number_of_Virtual_Meetings         15000 non-null  int64
 9   Work_Life_Balance_Rating           15000 non-null  int64
 10  Stress_Level                       15000 non-null  object
 11  Mental_Health_Condition            8847 non-null   object
 12  Access_to_Mental_Health_Resources  15000 non-null  object
 13  Productivity_Change                15000 non-null  object
 14  Social_Isolation_Rating            15000 non-null  int64
 15  Satisfaction_with_Remote_Work      15000 non-null  object
 16  Company_Support_for_Remote_Work    15000 non-null  int64
 17  Physical_Activity                  10113 non-null  object
 18  Sleep_Quality                      15000 non-null  object
 19  Region                             15000 non-null  object
dtypes: int64(7), object(13)
memory usage: 2.3+ MB

In [5]:
health_remote_df['Job_Role'].nunique()

7

In [6]:
health_remote_df['Industry'].nunique()

7

In [7]:
unique_items_list = health_remote_df['Job_Role'].unique().tolist()
unique_items_list

['HR',
 'Data Scientist',
 'Software Engineer',
 'Sales',
 'Marketing',
 'Designer',
 'Project Manager']

In [8]:
unique_items_list = health_remote_df['Industry'].unique().tolist()
unique_items_list

['Healthcare',
 'IT',
 'Education',
 'Finance',
 'Consulting',
 'Manufacturing',
 'Retail']

In [9]:
health_remote_df['Region'].value_counts()

Region
Oceania          2601
Africa           2580
Europe           2520
Asia             2487
South America    2481
North America    2331
Name: count, dtype: int64